name: Output Extractor
description: Extracts the outputs from all job steps up to the point the action was run
author: casconem

inputs:
  stepdata:
    description: the job's step data object
    required: true

outputs:
  config_output:
    description: the config_data object with new values if any

runs:
  using: node20
  main: dist/index.js