name: Output Extractor
description: Extracts the outputs from all job steps up to the point the action was run.
author: casconem

inputs:
  stepdata:
    description: step data
    required: true
    default: '{}'

outputs:
  finaloutput:
    description: the finalized params

runs:
  using: node20
  main: dist/index.js