name: Steps Context POC

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run:  npm ci

      - name: create out1
        id: out1
        run: echo 'build.snyk.status="Hello, world!"' >> $GITHUB_OUTPUT

      - name: create out2
        id: out2
        run: echo 'deploy.imageTag="where am i"' >> $GITHUB_OUTPUT

      - name: load ts action
        id: extractor
        uses: ./
        with:
          stepdata: ${{ toJSON(steps) }}

      - name: print ts action output
        id: printts
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY 
          echo "${{ toJSON(steps.extractor.outputs.finaloutput) }} | jq" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
