name: Steps Context POC

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run:  npm ci

      - name: create out1
        id: out1
        run: echo 'build.snyk.status="Hello, world!"' >> $GITHUB_OUTPUT

      - name: create out2
        id: out2
        run: echo 'deploy.imageTag="where am i"' >> $GITHUB_OUTPUT

      - name: mock config env
        run: |
          # npm install -g jq
          echo '{
            "app": {
              "ecrRepo": "389667733616.dkr.ecr.us-east-1.amazonaws.com",
              "basegitUrl": "mdpgit-live.app.mis.tld/scm",
              "gitOpsBranch": "deployment",
              "vault_url": "url will be loaded from vault_service_account.yaml",
              "devxApiUrl": null
            },
            "build": {
              "JAVA": "gradle",
              "ANGULAR": "angular",
              "PYTHON": "liquibase",
              "NODEJS": "nodejs",
              "DOTNETCORE": "python",
              "SPRINGNATIVE": "springnative",
              "SPRINGBOOT": "springboot"
            },
            "config": {
              "appId": 13234,
              "jiraKey": "EMTN",
              "appName": "e-exp-api",
              "liveTests": false,
              "performanceTests": false,
              "prod": true
            }
          }' | jq -c . > config_data.json
          echo CONFIG_DATA=$(cat config_data.json) >> $GITHUB_ENV
      - name: echo config
        run: echo $CONFIG_DATA

      - name: load ts action
        id: extractor
        uses: ./
        with:
          stepdata: ${{ toJSON(steps) }}

      - name: print ts action output
        id: printts
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY 
          echo "${{ toJSON(steps.extractor.outputs.finaloutput) }} | jq" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
