name: Steps Context POC

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # read mock-data.json into CONFIG_DATA
      - name: get mock config env
        run: echo "CONFIG_DATA=$(cat mock-data.json | jq . -c)" >> $GITHUB_ENV

      - name: create action1 output
        id: action1
        run: echo 'config.build.JAVA=tester' >> $GITHUB_OUTPUT

      - name: create action2 output
        id: action2
        run: echo 'config.deploy.imageTag=abc123.lloool:34324' >> $GITHUB_OUTPUT

      - name: an output that should not be captured
        id: ignored_output
        run: |
          echo 'some.other.output="i should not be here"' >> $GITHUB_OUTPUT
          echo 'some-other-output="i should also not be here"' >> $GITHUB_OUTPUT

      - name: a step with multiple outputs
        id: multioutput
        run: |
          echo 'config.deploy.imageTag=abc123.lloool:34324' >> $GITHUB_OUTPUT
          echo 'config.deploy.imageName=abc123.lloool' >> $GITHUB_OUTPUT

      - name: print steps
        run: echo "${{ toJSON(steps) }}"

      # output: config_output
      - name: load ts action
        id: extractor
        uses: ./
        with:
          stepdata: ${{ toJSON(steps) }}

      # - name: print ts action output
      #   id: printts
      #   run: |
      #     echo "finalized config_data" >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY 
      #     echo "${{ toJSON(steps.extractor.outputs.config_output) }}" >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
